# Generated by Django 5.2.6 on 2025-09-25 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('change_type', models.CharField(choices=[('service_create', 'Service Creation'), ('service_update', 'Service Update'), ('service_delete', 'Service Delete'), ('schema_create', 'Schema Creation'), ('schema_update', 'Schema Update'), ('schema_delete', 'Schema Delete'), ('policy_update', 'Policy Update')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('change_data', models.JSONField(help_text='JSON data containing the proposed changes')),
                ('original_data', models.JSONField(blank=True, help_text='Original data before change (for updates)', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('justification', models.TextField(blank=True, help_text='Why this change is needed')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action_type', models.CharField(choices=[('change_requested', 'Change Requested'), ('change_approved', 'Change Approved'), ('change_rejected', 'Change Rejected'), ('change_applied', 'Change Applied'), ('emergency_override', 'Emergency Override')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_data', models.JSONField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval_system.pendingchange')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signature_hash', models.CharField(help_text='SHA-256 hash of approval details', max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('approval_notes', models.TextField(blank=True)),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pending_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='approval_system.pendingchange')),
            ],
            options={
                'unique_together': {('pending_change', 'signed_by')},
            },
        ),
    ]
