# Generated by Django 4.2.14 on 2025-11-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_blocking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='country',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
