# Generated by Django 5.2.5 on 2025-08-29 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('method', models.CharField(max_length=10)),
                ('payload_size', models.IntegerField()),
                ('user_agent', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviourAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('anomaly_type', models.CharField(max_length=100)),
                ('risk_score', models.FloatField()),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detected_by', models.CharField(choices=[('rule', 'Rule-Based'), ('ml', 'IsolationForest')], default='rule', max_length=20)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='ai_behaviour.behaviourlogs')),
            ],
        ),
    ]
