# Generated by Django 5.2.5 on 2025-08-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TlsAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('issuer', models.TextField()),
                ('expires', models.DateTimeField()),
                ('serial_number', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
