# Generated by Django 4.2.14 on 2025-10-22 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ops_services", "0003_alter_service_host_name"),
        ("decision_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Service that handled this request (can be null if service deleted).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_logs",
                to="ops_services.service",
            ),
        ),
    ]
