# Generated by Django 4.2.14 on 2025-11-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_engine', '0002_requestlog_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='hmac_signature_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
