# Generated by Django 4.2.14 on 2025-11-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_engine', '0003_requestlog_hmac_signature_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='session_duration_ms',
            field=models.BigIntegerField(blank=True, help_text='Duration of session in milliseconds for successful requests', null=True),
        ),
    ]
