# Generated by Django 5.2.6 on 2025-09-25 09:05

import ops.ops_services.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_base_url', models.URLField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('routing_secret', models.CharField(default=ops.ops_services.models.Service.generate_secret, help_text='Unique secret used to sign routing headers (HMAC).', max_length=128)),
                ('allowed_origins', models.TextField(blank=True, help_text='Comma separated list of allowed origins for this service, e.g. https://foo.com, https://bar.com')),
                ('allowed_paths', models.TextField(blank=True, help_text='Comma-separated list of allowed path prefixes (e.g., /api/, /v1/health)')),
                ('allowed_methods', models.TextField(blank=True, help_text='Comma-separated list of allowed HTTP methods (e.g., GET, POST)')),
                ('allowed_schemes', models.TextField(blank=True, default='https', help_text='Comma-separated list of allowed URL schemes (e.g., https)')),
            ],
        ),
    ]
