# Generated by Django 5.2.6 on 2025-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='host_name',
            field=models.CharField(default='default.example.com', help_text='Hostname or domain name handled by this service (e.g., app1.situswaf.com)', max_length=255),
            preserve_default=False,
        ),
    ]
