# Generated by Django 4.2.14 on 2025-10-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops_services", "0002_service_host_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="host_name",
            field=models.CharField(
                help_text="Hostname or domain name handled by this service (e.g., app1.situswaf.com)",
                max_length=255,
            ),
        ),
    ]
