# Generated by Django 5.2.5 on 2025-08-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops_services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('schema_json', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, db_column='service_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='json_schemas', to='ops_services.service', to_field='uuid')),
            ],
        ),
    ]
