# Generated by Django 5.2.6 on 2025-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_enforcer', '0001_initial'),
        ('ops_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonschema',
            name='method',
            field=models.CharField(default='POST', help_text='GET, POST, etc.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jsonschema',
            name='rollout_mode',
            field=models.CharField(choices=[('monitor', 'Monitor only'), ('enforce', 'Strict enforcement')], default='monitor', help_text='If enforce, invalid schema will be blocked. If monitor, only logged.', max_length=16),
        ),
        migrations.AddField(
            model_name='jsonschema',
            name='version',
            field=models.CharField(default='v1', help_text='Schema version, e.g., v1, v2-beta', max_length=32),
        ),
        migrations.AlterField(
            model_name='jsonschema',
            name='endpoint',
            field=models.CharField(help_text='Path prefix or full path, e.g. /api/data', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='jsonschema',
            unique_together={('service', 'endpoint', 'method', 'version')},
        ),
    ]
