# Generated by Django 5.2.6 on 2025-09-26 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_reputation', '0001_initial'),
        ('ops_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalIPList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('list_type', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ops_services.service')),
            ],
        ),
    ]
